baseURL = "https://baku4893.netlify.app/"
languageCode = "ja"
title = "いろいろ"
theme="simple-style"
defaultContentLanguage="ja"
hasCJKLanguage=true
mainSections=["blog"]

[params]
subtitle = "Sub title of the site"
description = "456ervwrfvervserverve"
