baseURL = "https://baku4893.netlify.app/"
languageCode = "ja"
title = "いろいろ備忘録(仮)"
theme="inkblotty"
defaultContentLanguage="ja"
hasCJKLanguage=true
pluralizeListTitles = false
sectionPagesMenu = "main"

[permalinks]
	"ブログ" = "/:section/:year/:month/:day/:slug"
	"購入物" = "/:section/:year/:month/:day/:slug"

[taxonomies]
	tag = "tags"
	category = "categories"
	archive = "archives"

[params]
	readmore = true

[[menu.main]]
        identifier = "ブログ"
        name = "ブログ"
        url = "/ブログ/"
        weight = 1

[[menu.main]]
	identifier = "購入物"
	name = "購入物"
	url = "/購入物/"
	weight = 2

[[menu.main]]
	identifier = "RSS"
	name = "RSS"
	url = "/index.xml"
	weight = 4
#git add .;git commit -m "update";git push
