baseURL = "https://baku4893.netlify.app/"
languageCode = "ja"
title = "いろいろ(仮)"
theme="inkblotty"
defaultContentLanguage="ja"
hasCJKLanguage=true
pluralizeListTitles = false

[permalinks]
	post = "/:slug/"
	page = "/:slug/"

[taxonomies]
	tag = "tags"
	category = "categories"
	archive = "archives"

[params]
	readmore = true

[[menu.main]]
	identifier = "blog"
	name = "ブログ"
	url = "/blog/"
	weight =1

[[menu.main]]
	identifier = "購入物"
	name = "購入物"
	url = "/購入物/"
	weight = 2

[[menu.main]]
	identifier = "about"
	name = "about"
	url = "/about/"
	weight = 3

[[menu.main]]
	identifier = "RSS"
	name = "RSS"
	url = "/index.xml"
	weight = 4
#git add .;git commit -m "update";git push
