baseURL = "https://baku4893.netlify.app/"
languageCode = "ja"
title = "いろいろ(仮)"
theme="blackburn"
defaultContentLanguage="ja"
hasCJKLanguage=true
mainSections=["blog"]

[taxonomies]
  tag = "tags"
  category = "categories"

[param]
subtitle="備忘録的なサイト（てきとう"
