baseURL = "https://baku4893.netlify.app/"
languageCode = "ja"
title = "いろいろ(仮)"
theme="inkblotty"
defaultContentLanguage="ja"
hasCJKLanguage=true

[permalinks]
	post = "/:slug/"
	page = "/:slug/"

[taxonomies]
	tag = "tags"
	category = "categories"
	archive = "archives"

[params]
	readmore = true

[[menu.main]]
	identifier = "home"
	name = "home"
	url = "/"
	weight = 1
	
[[menu.main]]
	identifier = "blog"
	name = "blog"
	url = "/blog/"
	weight = 2


[[menu.main]]
	identifier = "about"
	name = "about"
	url = "/about/"
	weight = 3
#git add .;git commit -m "update";git push